version: '3'

services:
    wordpress:
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks: 
      - webnet
      - dbnet

volumes:
    db_data:

networks:
  dbnet:
    driver: bridge
  webnet:
    driver: bridge